source 'https://rubygems.org'
gem 'bundix', github: 'manveru/bundix'
gem 'gli', '~> 2.17.1'
gem 'json'
gem 'md2man'
gem 'rainbow', '~> 3.0.0'
gem 'rake'
gem 'require_all', '~> 2.0.0'
gem 'tty-command', '~> 0.10.1'
gem 'tty-cursor', '~> 0.7.1'
gem 'tty-pager', '~> 0.14.0'
gem 'tty-progressbar', '~> 0.18.2'
gem 'tty-spinner', '~> 0.9.3'
gem 'vpsfree-client', '~> 0.11.0'
