package core

// Exact templates from Ruby cc40679 lib/confctl/cli/configuration.rb.
// Keep file bytes and declaration order separate from filesystem operations.
const (
	configurationTemplate0 = `(import ./cluster.nix) ++ [
  # Place for custom modules
]
`
	configurationTemplate1 = `# This file is generated by confctl, changes will be lost
[]
`
	configurationTemplate2 = `{ config, ... }:
{
  confctl = {
    # list.columns = [
    #   "name"
    #   "spin"
    #   "host.fqdn"
    # ];
  };
}
`
	configurationTemplate3 = `{ lib }:
{
  # Place to load custom data sets
  sshKeys = import ./ssh-keys.nix;
}
`
	configurationTemplate4 = `rec {
  admins = [
    # someone
  ];

  someone = "...ssh public key...";
}
`
	configurationTemplate5 = `{ config, pkgs, confData, ... }:
{
  time.timeZone = "Europe/Amsterdam";

  services.openssh.enable = true;

  environment.systemPackages = with pkgs; [
    vim
    screen
  ];

  users.users.root.openssh.authorizedKeys.keys = with confData.sshKeys; admins;
}
`
	configurationTemplate6 = `rec {
  shared = [
    # Modules not dependent on spin
  ];

  nixos = shared ++ [
    # Modules only for NixOS
  ];

  vpsadminos = shared ++ [
    # Modules only for vpsAdminOS
  ];
}
`
	configurationTemplate7 = `{
  description = "confctl configuration (flake)";

  inputs = {
    confctl.url = "github:vpsfreecz/confctl";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # vpsadminos.url = "github:vpsfreecz/vpsadminos/staging";
    # vpsadminos.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = inputs@{ self, confctl, ... }:
    let
      channels = {
        nixos-unstable = { nixpkgs = "nixpkgs"; };

        # vpsadminos = {
        #   nixpkgs = "nixpkgs";
        #   vpsadminos = "vpsadminos";
        # };
      };

      confctlOutputs = confctl.lib.mkConfctlOutputs {
        confDir = ./.;
        inherit inputs channels;
      };
    in
    {
      confctl = confctlOutputs;

      devShells.x86_64-linux.default = confctl.lib.mkConfigDevShell {
        system = "x86_64-linux";
        mode = "minimal";
      };
    };
}
`
)

type configurationTemplate struct {
	path, text string
	directory  bool
}

var configurationInitTemplates = []configurationTemplate{
	{path: "cluster", directory: true},
	{path: "cluster/module-list.nix", text: configurationTemplate0},
	{path: "cluster/cluster.nix", text: configurationTemplate1},
	{path: "configs", directory: true},
	{path: "configs/confctl.nix", text: configurationTemplate2},
	{path: "data", directory: true},
	{path: "data/default.nix", text: configurationTemplate3},
	{path: "data/ssh-keys.nix", text: configurationTemplate4},
	{path: "environments", directory: true},
	{path: "environments/base.nix", text: configurationTemplate5},
	{path: "modules", directory: true},
	{path: "modules/module-list.nix", text: configurationTemplate6},
	{path: "flake.nix", text: configurationTemplate7},
}

const configurationMachineModule = `{ config, ... }:
{
  cluster."%s" = {
    spin = "nixos";
    inputs.channels = [ "nixos-unstable" ];
    host = { name = "machine"; domain = "example.com"; };
  };
}
`

const configurationMachineConfig = `{ config, pkgs, lib, ... }:
{
  imports = [
    %senvironments/base.nix
  ];

  # ... standard NixOS configuration ...

  networking.hostName = "%s";
}
`
