package core

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	ext "github.com/vpsfreecz/confctl/extension"
	"github.com/vpsfreecz/confctl/internal/cli"
)

func cliConfigurationOrigin(argv []string) (cli.Invocation, error) {
	return cli.BuiltinRegistry().Parse(argv)
}

type configurationHookRecord struct {
	Handler    string
	Phase      string
	Machines   []string
	Invocation ext.Invocation
}

// Real public SDK handlers run in supervised child processes. Each request
// crosses FD3/4 and the existing service/process boundary; none is linked in.
func TestConfigurationHookHelper(t *testing.T) {
	if os.Getenv("CONFCTL_CONFIGURATION_HOOK") != "1" {
		return
	}
	handlers := map[string]ext.Handler{}
	for _, name := range []string{"first", "a-second", "b-second", "third", "failure", "unreached"} {
		handlers[name] = func(ctx context.Context, c *ext.Client, in ext.Invocation) error {
			active := os.Getenv("CONFCTL_CONFIGURATION_ACTIVE")
			f, err := os.OpenFile(active, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
			if err != nil {
				return fmt.Errorf("hook overlap: %w", err)
			}
			_ = f.Close()
			defer os.Remove(active)
			if in.Event != "rediscover.after-write" || in.Action != "" || in.Generation != nil || in.SelectedNames != nil || len(in.Options) != 0 {
				return fmt.Errorf("incorrect rediscovery context: %#v", in)
			}
			if b, err := os.ReadFile(filepath.Join(in.Root, "cluster/cluster.nix")); err != nil || !strings.HasPrefix(string(b), "# This file is generated by confctl") {
				return fmt.Errorf("hook ran before inventory replacement: %s %v", b, err)
			}
			settings, err := c.Settings(ctx)
			if err != nil {
				return err
			}
			snapshot, err := c.Select(ctx, ext.Selection{Managed: "all"})
			if err != nil {
				return err
			}
			record := configurationHookRecord{Handler: name, Phase: str(settings["phase"]), Machines: snapshot.Names(), Invocation: in}
			f, err = os.OpenFile(os.Getenv("CONFCTL_CONFIGURATION_CAPTURE"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0600)
			if err != nil {
				return err
			}
			err = json.NewEncoder(f).Encode(record)
			_ = f.Close()
			if err != nil {
				return err
			}
			if err = os.WriteFile(filepath.Join(in.Root, "hook-state"), []byte(name), 0644); err != nil {
				return err
			}
			if name == "failure" {
				return fmt.Errorf("requested hook failure")
			}
			return nil
		}
	}
	ext.Serve(handlers, []string{"settings.get", "machines.select"})
}

// This is a process fixture, not a replacement evaluator inside core. It emits
// settings/inventory from live files only when the real service asks Nix for it.
func TestConfigurationNixHelper(t *testing.T) {
	if os.Getenv("CONFCTL_CONFIGURATION_NIX") != "1" {
		return
	}
	if _, err := os.Stat(os.Getenv("CONFCTL_CONFIGURATION_ACTIVE")); err != nil {
		t.Fatal("Nix request outside a live hook", err)
	}
	phase, err := os.ReadFile("hook-state")
	if err != nil {
		t.Fatal(err)
	}
	args := os.Args
	installable := args[len(args)-1]
	switch installable {
	case ".#confctl.settings":
		time.Sleep(5 * time.Millisecond)
		_ = json.NewEncoder(os.Stdout).Encode(map[string]any{"phase": string(phase), "nix": map[string]any{"maxJobs": "auto", "impureEval": false}})
	case ".#confctl.machinesJson":
		b, err := os.ReadFile("cluster/cluster.nix")
		if err != nil {
			t.Fatal(err)
		}
		machines := map[string]any{}
		for _, line := range strings.Split(string(b), "\n") {
			if !strings.HasPrefix(line, "  ./") || !strings.HasSuffix(line, "/module.nix") {
				continue
			}
			name := strings.TrimSuffix(strings.TrimPrefix(line, "  ./"), "/module.nix")
			machines[name] = map[string]any{"name": name, "clusterName": name, "metaConfig": map[string]any{"managed": true}}
		}
		name := "phase-" + string(phase)
		machines[name] = map[string]any{"name": name, "clusterName": name, "metaConfig": map[string]any{"managed": true}}
		b, _ = json.Marshal(machines)
		root, _ := os.Getwd()
		out := filepath.Join(root, ".confctl/fixture-machines.json")
		if err = os.MkdirAll(filepath.Dir(out), 0755); err != nil {
			t.Fatal(err)
		}
		if err = os.WriteFile(out, b, 0644); err != nil {
			t.Fatal(err)
		}
		_ = json.NewEncoder(os.Stdout).Encode([]any{map[string]any{"outputs": map[string]any{"out": out}}})
	default:
		t.Fatal("unexpected Nix installable", args)
	}
	os.Exit(0)
}

func configurationHookRegistry(failure bool) Registry {
	argv := []string{os.Args[0], "-test.run=^TestConfigurationHookHelper$"}
	r := Registry{Schema: 1, Extensions: []Registration{
		{ID: "omega", Protocol: ext.Version{Major: 1}, Argv: argv, Hooks: []Hook{{Event: "rediscover.after-write", Handler: "third", Order: 1}}},
		{ID: "zeta", Protocol: ext.Version{Major: 1}, Argv: argv, Hooks: []Hook{{Event: "rediscover.after-write", Handler: "first", Order: 0}}},
		{ID: "alpha", Protocol: ext.Version{Major: 1}, Argv: argv, Hooks: []Hook{{Event: "rediscover.after-write", Handler: "b-second", Order: 1}, {Event: "rediscover.after-write", Handler: "a-second", Order: 1}}},
	}}
	if failure {
		r.Extensions[0].Hooks = append(r.Extensions[0].Hooks, Hook{Event: "rediscover.after-write", Handler: "failure", Order: 2}, Hook{Event: "rediscover.after-write", Handler: "unreached", Order: 3})
	}
	return r
}

func configurationHookEnvironment(t *testing.T, root string) string {
	t.Helper()
	t.Setenv("CONFCTL_CONFIGURATION_HOOK", "1")
	t.Setenv("CONFCTL_CONFIGURATION_NIX", "1")
	artifacts := t.TempDir()
	capture := filepath.Join(artifacts, "hooks.jsonl")
	t.Setenv("CONFCTL_CONFIGURATION_CAPTURE", capture)
	t.Setenv("CONFCTL_CONFIGURATION_ACTIVE", filepath.Join(artifacts, "active"))
	configurationFile(t, root, "hook-state", "base")
	return capture
}

func checkConfigurationHookRecords(t *testing.T, capture string, argv []string, names []string, failure bool) {
	t.Helper()
	b, err := os.ReadFile(capture)
	if err != nil {
		t.Fatal(err)
	}
	wantHandlers := []string{"first", "a-second", "b-second", "third"}
	wantIDs := []string{"zeta", "alpha", "alpha", "omega"}
	wantPhases := []string{"base", "first", "a-second", "b-second"}
	if failure {
		wantHandlers = append(wantHandlers, "failure")
		wantIDs = append(wantIDs, "omega")
		wantPhases = append(wantPhases, "third")
	}
	lines := strings.Split(strings.TrimSpace(string(b)), "\n")
	if len(lines) != len(wantHandlers) {
		t.Fatal("missing/out-of-order hooks or hook ran after failure", string(b))
	}
	for i, line := range lines {
		var record configurationHookRecord
		if err := json.Unmarshal([]byte(line), &record); err != nil {
			t.Fatal(err)
		}
		wantNames := append(append([]string(nil), names...), "phase-"+wantPhases[i])
		wantArgs := append([]string(nil), argv[1:]...)
		if record.Handler != wantHandlers[i] || record.Invocation.ExtensionID != wantIDs[i] || record.Phase != wantPhases[i] || !reflect.DeepEqual(record.Machines, wantNames) || !reflect.DeepEqual(record.Invocation.OriginCommand, argv[:1]) || !reflect.DeepEqual(record.Invocation.Arguments, wantArgs) || !reflect.DeepEqual(record.Invocation.RawArgv, argv) {
			t.Fatalf("stale inventory/settings or wrong origin/order: %#v, argv=%q names=%q", record, argv, wantNames)
		}
	}
}

func TestConfigurationNativeMainHookOriginsAndFreshServices(t *testing.T) {
	for _, argv := range [][]string{{"rediscover"}, {"add", "nested/new"}, {"rename", "old", "nested/new"}} {
		t.Run(argv[0], func(t *testing.T) {
			root := t.TempDir()
			configurationMachine(t, root, "old")
			capture := configurationHookEnvironment(t, root)
			r := bindTestRegistry(t, root, configurationHookRegistry(false))
			path := writeTestRegistry(t, r)
			code, stdout, stderr := configurationCLI(t, root, argv, path, "022")
			if code != 0 || !strings.HasSuffix(stdout, "replace cluster/cluster.nix\n") || stderr != "" {
				t.Fatal(code, stdout, stderr)
			}
			names := []string{"old"}
			if argv[0] == "add" {
				names = []string{"nested/new", "old"}
			} else if argv[0] == "rename" {
				names = []string{"nested/new"}
			}
			// Fixture JSON is key-sorted; phase-* sorts after these host names.
			checkConfigurationHookRecords(t, capture, argv, names, false)
		})
	}
}

func TestConfigurationWarmCachesAndHookFailureRetainWrites(t *testing.T) {
	root := t.TempDir()
	configurationMachine(t, root, "new")
	capture := configurationHookEnvironment(t, root)
	r := bindTestRegistry(t, root, configurationHookRegistry(true))
	tools, marker := configurationTools(t)
	t.Setenv("PATH", tools+":"+os.Getenv("PATH"))
	// Five serial SDK children each request settings, evaluator settings and
	// inventory: fifteen Nix helpers also run. Successful race-instrumented
	// children finalize on exit, so allow this finite sequence a larger budget.
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	origin, err := cliConfigurationOrigin([]string{"rediscover"})
	if err != nil {
		t.Fatal(err)
	}
	e := &Engine{Root: root, Context: ctx, Inventory: []Machine{{Name: "stale"}}, SettingsCache: map[string]any{"phase": "stale"}}
	code, err := e.Rediscover(configurationOperation{Registry: r, Origin: origin})
	if code == 0 || err == nil || !strings.Contains(err.Error(), "requested hook failure") || e.Inventory != nil || e.SettingsCache != nil || ctx.Err() != nil {
		t.Fatal("failed invocation lost invalidation/barrier", code, err, e.Inventory, e.SettingsCache, ctx.Err())
	}
	checkConfigurationHookRecords(t, capture, []string{"rediscover"}, []string{"new"}, true)
	if got := configurationRead(t, root, "cluster/cluster.nix"); !strings.Contains(got, "./new/module.nix") || configurationRead(t, root, "hook-state") != "failure" {
		t.Fatal("failed hook undid completed writes", got)
	}
	if _, err := os.Stat(marker); !os.IsNotExist(err) {
		t.Fatal("hook ran an unexpected tool", err)
	}
	if _, err := os.Stat(os.Getenv("CONFCTL_CONFIGURATION_ACTIVE")); !os.IsNotExist(err) {
		t.Fatal("hook/service work still active after failure", err)
	}
}
