require 'securerandom'

module ConfCtl::Cli
  class Configuration < Command
    DIR_MODE = 0755
    FILE_MODE = 0644

    def rediscover
      hosts = discover_dir(File.join(ConfCtl.conf_dir, 'cluster')).sort

      replace_file(File.join(ConfCtl.conf_dir, 'cluster', 'cluster.nix')) do |f|
        f.puts("# This file is generated by confctl, changes will be lost")
        f.puts("[")
        
        hosts.each do |host|
          f.puts("  ./#{host}/module.nix")
        end
        
        f.puts("]")
      end
    end

    protected
    def discover_dir(dir_path, rel_path = nil)
      ret = []
      
      Dir.entries(dir_path).each do |v|
        entry_abs_path = File.join(dir_path, v)
        next if %w(. ..).include?(v) || !File.directory?(entry_abs_path)

        entry_rel_path = File.join(*[rel_path, v].compact)
        
        if File.exist?(File.join(entry_abs_path, 'module.nix')) \
           && File.exist?(File.join(entry_abs_path, 'config.nix'))
          ret << entry_rel_path
        end

        ret.concat(discover_dir(entry_abs_path, entry_rel_path))
      end

      ret
    end

    def replace_file(name)
      replacement = "#{name}.new-#{SecureRandom.hex(3)}"

      File.open(replacement, 'w', FILE_MODE) do |f|
        yield(f)
      end

      File.rename(replacement, name)
    end
  end
end
