# frozen_string_literal: true

require 'fileutils'
require 'json'
require 'open3'

module ConfctlTestHelpers
  STORE_PATH_RE = %r{/nix/store/[0-9a-z]{32}-[^\s'"]+}

  def confctl_setup!(bin:, src:, conf_dir:, home_dir:, nix_path: nil)
    @confctl_bin = bin
    @confctl_src = src
    @conf_dir = conf_dir
    @home_dir = home_dir
    @nix_path = nix_path
  end

  def confctl_bin
    @confctl_bin || raise('confctl_setup! must be called before confctl helpers are used')
  end

  def confctl_src
    @confctl_src || raise('confctl_setup! must be called before confctl helpers are used')
  end

  def conf_dir
    @conf_dir || raise('confctl_setup! must be called before confctl helpers are used')
  end

  def home_dir
    @home_dir || raise('confctl_setup! must be called before confctl helpers are used')
  end

  def nix_path
    @nix_path
  end

  def run_local(argv, chdir: nil, env: {})
    kwargs = {}
    kwargs[:chdir] = chdir if chdir
    out, err, status = Open3.capture3(env, *argv, **kwargs)
    [out, err, status]
  end

  def run_local!(argv, chdir: nil, env: {})
    out, err, status = run_local(argv, chdir: chdir, env: env)

    return [out, err] if status.success?

    msg = []
    msg << "Command failed: #{argv.join(' ')}"
    msg << "Exit status: #{status.exitstatus}"
    msg << "STDOUT:\n#{out}" unless out.empty?
    msg << "STDERR:\n#{err}" unless err.empty?
    raise msg.join("\n\n")
  end

  def prepare_fixture_dir!(path, template: 'example-flake')
    FileUtils.rm_rf(path)
    FileUtils.mkdir_p(path)

    run_local!(['cp', '-r', "#{File.join(confctl_src, template)}/.", path])
    run_local!(['chmod', '-R', 'u+w', path])

    # Test fixtures regenerate local state such as swpins pins and channels.
    # Drop any copied state from the repository template to keep runs deterministic.
    %w[.bin .confctl .gems .man swpins].each do |dir|
      FileUtils.rm_rf(File.join(path, dir))
    end
  end

  def nix_escape_string(str)
    str.gsub('\\', '\\\\').gsub('"', '\\"')
  end

  def write_admin_ssh_keys!(path, pubkey, admin_name: 'someone')
    escaped_key = nix_escape_string(pubkey)

    File.write(File.join(path, 'data/ssh-keys.nix'), <<~NIX)
      rec {
        admins = [ #{admin_name} ];

        #{admin_name} = "#{escaped_key}";
      }
    NIX
  end

  def write_cluster_modules!(path, entries)
    modules = entries.map { |v| "  ./#{v}" }.join("\n")

    File.write(File.join(path, 'cluster/cluster.nix'), <<~NIX)
      # This file is generated by confctl, changes will be lost
      [
      #{modules}
      ]
    NIX
  end

  def init_fixture_repo!(path, message: 'fixture: initial')
    run_local!(%w[git init], chdir: path)
    run_local!(%w[git config user.email confctl-tests@example.invalid], chdir: path)
    run_local!(%w[git config user.name confctl-tests], chdir: path)
    run_local!(%w[git add .], chdir: path)
    run_local!(['git', 'commit', '-m', message], chdir: path)
  end

  def setup_ssh_home!(path)
    FileUtils.rm_rf(path)
    ssh_dir = File.join(path, '.ssh')
    key_path = File.join(ssh_dir, 'id_ed25519')
    FileUtils.mkdir_p(ssh_dir)

    run_local!(['ssh-keygen', '-q', '-t', 'ed25519', '-N', '', '-f', key_path])

    File.write(File.join(ssh_dir, 'config'), <<~CFG)
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile #{key_path}
        IdentitiesOnly yes
        ConnectTimeout 10
        ServerAliveInterval 5
        ServerAliveCountMax 6
        LogLevel ERROR
    CFG

    File.chmod(0o700, ssh_dir)
    File.chmod(0o600, key_path)
    File.chmod(0o600, "#{key_path}.pub")
    File.chmod(0o600, File.join(ssh_dir, 'config'))

    File.read("#{key_path}.pub").strip
  end

  def install_pubkey!(machine, pubkey, timeout: 300)
    wait_for_block(name: "install SSH key on #{machine.name}", timeout:) do
      machine.succeeds('mkdir -p /root/.ssh && chmod 700 /root/.ssh')
      machine.succeeds("cat > /root/.ssh/authorized_keys <<'EOF'\n#{pubkey}\nEOF\nchmod 600 /root/.ssh/authorized_keys")
      true
    rescue EOFError, OsVm::MachineShellClosed, OsVm::CommandFailed
      false
    end
  end

  def confctl_env
    ssh_config = File.join(home_dir, '.ssh', 'config')
    ssh_key = File.join(home_dir, '.ssh', 'id_ed25519')
    ssh_opts = [
      "-F #{ssh_config}",
      "-i #{ssh_key}",
      '-o IdentitiesOnly=yes',
      '-o StrictHostKeyChecking=no',
      '-o UserKnownHostsFile=/dev/null',
      '-o LogLevel=ERROR',
      '-o ConnectTimeout=10'
    ].join(' ')

    {
      'HOME' => home_dir,
      'CONFCTL_TTY' => '0',
      'CONFCTL_SSH_CONFIG' => ssh_config,
      'NIX_SSHOPTS' => ssh_opts,
      'NIX_PATH' => [nix_path, ENV.fetch('NIX_PATH', nil)].compact.join(':'),
      'NIX_CONFIG' => [ENV.fetch('NIX_CONFIG', nil), 'sandbox = false'].compact.join("\n"),
      'NO_COLOR' => '1',
      'PAGER' => ''
    }
  end

  def confctl(*args)
    run_local([confctl_bin, *args], chdir: conf_dir, env: confctl_env)
  end

  def confctl!(*args)
    run_local!([confctl_bin, *args], chdir: conf_dir, env: confctl_env)
  end

  def confctl_ssh(machine, *remote_argv)
    confctl('ssh', '--yes', machine, *remote_argv.map(&:to_s))
  end

  def confctl_ssh!(machine, *remote_argv)
    confctl!('ssh', '--yes', machine, *remote_argv.map(&:to_s))
  end

  def extract_store_path(text)
    text.to_s.scan(STORE_PATH_RE).last
  end

  def confctl_remote_realpath(machine, path)
    out, = confctl_ssh!(machine, 'realpath', path)
    store_path = extract_store_path(out)
    return store_path unless store_path.nil?

    raise "unable to parse store path from confctl ssh output for #{machine}:#{path}: #{out.inspect}"
  end

  def confctl_store_path_exists!(machine, store_path)
    confctl_ssh!(machine, 'test', '-e', store_path)
  end

  def confctl_machine_state(machine)
    {
      profile: confctl_remote_realpath(machine, '/nix/var/nix/profiles/system'),
      current: confctl_remote_realpath(machine, '/run/current-system')
    }
  end

  def wait_for_confctl_connectivity!(expected_successes:, timeout: 120)
    deadline = Time.now + timeout

    loop do
      out, _err, status = confctl('test-connection', '--yes')
      return out if status.success? && out.include?("#{expected_successes} successful")

      raise "confctl test-connection did not report #{expected_successes} successful hosts in #{timeout}s" if Time.now >= deadline

      sleep(2)
    end
  end

  def confctl_generation_info(host, selector = 'current')
    host_dir = File.join(conf_dir, '.confctl', 'generations', host.tr('/', ':'))

    generation_name =
      if selector == 'current'
        current_link = File.join(host_dir, 'current')
        File.basename(File.readlink(current_link))
      else
        selector
      end

    json_path = File.join(host_dir, generation_name, 'generation.json')
    JSON.parse(File.read(json_path)).merge('name' => generation_name)
  end
end

TestRunner::TestEvaluator.include(ConfctlTestHelpers)
